# Project: Canadian Heritage Funding
# Authors: Artan Zandian, Joyce Wang, Amelia Tang, Wenxin Xiang
# Docker-compose Usage: docker-compose run --rm report-env make -C //home//jovyan//work all

services:
  report-env:
    image: artanzandian/canadian_heritage_funding
    ports:
      - "8888:8888"
    volumes:
      - .://home//jovyan//work
